on: 
  workflow_dispatch:
    inputs:
      Branch:
        description: 'select a branch to run workflow'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - dev
        - qa
      RUNENV:
        description: 'select a environment to deploy '     
        required: true
        default: 'cn' 
        type: choice
        options:
        - cn
        - jp
        - us

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch: $Branch"
          echo "Environment: $RUNENV"
        env:
          Banch: ${{ inputs.Branch }}
          RUNENVIRONMENT: ${{ inputs.RUNENV }}
