name: Deploy Test

on: 
  workflow_dispatch:
    inputs:
      Branch:
        description: 'select a branch to run workflow'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - dev
        - qa
      RUNENV:
        description: 'select a environment to deploy '     
        required: true
        default: 'cn' 
        type: choice
        options:
        - cn
        - jp
        - us

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref:  ${{ inputs.Branch }}
          
      - run: |
          echo "Branch: ${{ inputs.Branch }}"
          echo "Environment: ${{ inputs.RUNENV }}"
          cat ./*

